
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package GramaticaJAVA;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AC = 6;
  public static final int CHAR = 12;
  public static final int RES = 36;
  public static final int EQUALS = 16;
  public static final int ENTERO = 32;
  public static final int INPUTI = 26;
  public static final int CASE = 43;
  public static final int DOUBLE = 11;
  public static final int INPUTD = 28;
  public static final int INT = 10;
  public static final int INPUTC = 27;
  public static final int PUNTOCOMA = 15;
  public static final int PRINTLN = 30;
  public static final int FOR = 23;
  public static final int CP = 5;
  public static final int NOT = 9;
  public static final int AND = 18;
  public static final int CARACTER = 34;
  public static final int OR = 20;
  public static final int OP = 40;
  public static final int CLASS = 3;
  public static final int DIV = 38;
  public static final int BOTHPOINT = 45;
  public static final int CC = 7;
  public static final int IF = 19;
  public static final int ID = 13;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int error = 1;
  public static final int MUL = 37;
  public static final int COMA = 17;
  public static final int CADENA = 14;
  public static final int BREAK = 44;
  public static final int VOID = 8;
  public static final int SWITCH = 42;
  public static final int REAL = 33;
  public static final int ELSE = 22;
  public static final int WHILE = 21;
  public static final int DEFAULT = 41;
  public static final int PUBLIC = 2;
  public static final int SUM = 35;
  public static final int MODUL = 39;
  public static final int AP = 4;
  public static final int PY = 31;
  public static final int PRINT = 29;
  public static final int DO = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "AP",
  "CP",
  "AC",
  "CC",
  "VOID",
  "NOT",
  "INT",
  "DOUBLE",
  "CHAR",
  "ID",
  "CADENA",
  "PUNTOCOMA",
  "EQUALS",
  "COMA",
  "AND",
  "IF",
  "OR",
  "WHILE",
  "ELSE",
  "FOR",
  "DO",
  "RETURN",
  "INPUTI",
  "INPUTC",
  "INPUTD",
  "PRINT",
  "PRINTLN",
  "PY",
  "ENTERO",
  "REAL",
  "CARACTER",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MODUL",
  "OP",
  "DEFAULT",
  "SWITCH",
  "CASE",
  "BREAK",
  "BOTHPOINT"
  };
}

