
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package GramaticaVisualBasic;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Y = 47;
  public static final int CHAR = 33;
  public static final int JAVA = 50;
  public static final int RES = 41;
  public static final int EQUALS = 25;
  public static final int ENTERO = 51;
  public static final int INPUTI = 19;
  public static final int CASE = 10;
  public static final int CONSL = 23;
  public static final int INPUTD = 20;
  public static final int INT = 27;
  public static final int INPUTC = 21;
  public static final int VB = 49;
  public static final int FOR = 29;
  public static final int CP = 46;
  public static final int AND = 38;
  public static final int NOT = 36;
  public static final int CARACTER = 53;
  public static final int FUN = 15;
  public static final int OR = 37;
  public static final int OP = 39;
  public static final int DIV = 43;
  public static final int UNTIL = 12;
  public static final int SELECT = 8;
  public static final int NEXT = 28;
  public static final int LOOP = 13;
  public static final int EXIT = 9;
  public static final int IF = 4;
  public static final int ELSE_IF = 7;
  public static final int ID = 48;
  public static final int DIM = 3;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int BYVAL = 18;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int COMA = 26;
  public static final int CADENA = 54;
  public static final int REAL = 52;
  public static final int MODULE = 17;
  public static final int ELSE = 6;
  public static final int CONSLN = 22;
  public static final int TO = 55;
  public static final int WHILE = 31;
  public static final int FLOAT = 34;
  public static final int PUBLIC = 14;
  public static final int THEN = 2;
  public static final int SUM = 40;
  public static final int END = 5;
  public static final int SALTO_LINEA = 35;
  public static final int AS = 24;
  public static final int AP = 45;
  public static final int MODUL = 44;
  public static final int SUB = 16;
  public static final int DO = 11;
  public static final int STEP = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "THEN",
  "DIM",
  "IF",
  "END",
  "ELSE",
  "ELSE_IF",
  "SELECT",
  "EXIT",
  "CASE",
  "DO",
  "UNTIL",
  "LOOP",
  "PUBLIC",
  "FUN",
  "SUB",
  "MODULE",
  "BYVAL",
  "INPUTI",
  "INPUTD",
  "INPUTC",
  "CONSLN",
  "CONSL",
  "AS",
  "EQUALS",
  "COMA",
  "INT",
  "NEXT",
  "FOR",
  "STEP",
  "WHILE",
  "RETURN",
  "CHAR",
  "FLOAT",
  "SALTO_LINEA",
  "NOT",
  "OR",
  "AND",
  "OP",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MODUL",
  "AP",
  "CP",
  "Y",
  "ID",
  "VB",
  "JAVA",
  "ENTERO",
  "REAL",
  "CARACTER",
  "CADENA",
  "TO"
  };
}

