
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package GramaticaC;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Y = 9;
  public static final int SCANF = 10;
  public static final int AC = 6;
  public static final int CONST = 33;
  public static final int CHAR = 15;
  public static final int CCOR = 35;
  public static final int RES = 41;
  public static final int EQUALS = 19;
  public static final int CALLPY = 56;
  public static final int ENTERO = 37;
  public static final int INPUTI = 29;
  public static final int CASE = 50;
  public static final int DOUBLE = 14;
  public static final int INPUTD = 31;
  public static final int INT = 13;
  public static final int INPUTC = 30;
  public static final int PUNTOCOMA = 18;
  public static final int FOR = 26;
  public static final int ACOR = 34;
  public static final int CP = 5;
  public static final int NOT = 47;
  public static final int AND = 21;
  public static final int CARACTER = 39;
  public static final int OR = 23;
  public static final int OP = 45;
  public static final int CLASS = 3;
  public static final int DIV = 43;
  public static final int CALLVB = 57;
  public static final int BOTHPOINT = 52;
  public static final int CC = 7;
  public static final int MAIN = 36;
  public static final int IF = 22;
  public static final int ID = 16;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int error = 1;
  public static final int INCLUDE = 53;
  public static final int MASCARA = 46;
  public static final int MUL = 42;
  public static final int GETCH = 12;
  public static final int COMA = 20;
  public static final int CADENA = 17;
  public static final int BREAK = 51;
  public static final int VOID = 8;
  public static final int SWITCH = 49;
  public static final int REAL = 38;
  public static final int INITJAVA = 54;
  public static final int ELSE = 25;
  public static final int WHILE = 24;
  public static final int DEFAULT = 48;
  public static final int PUBLIC = 2;
  public static final int CLEAR = 11;
  public static final int SUM = 40;
  public static final int CALLJAVA = 55;
  public static final int MODUL = 44;
  public static final int AP = 4;
  public static final int PRINT = 32;
  public static final int DO = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "AP",
  "CP",
  "AC",
  "CC",
  "VOID",
  "Y",
  "SCANF",
  "CLEAR",
  "GETCH",
  "INT",
  "DOUBLE",
  "CHAR",
  "ID",
  "CADENA",
  "PUNTOCOMA",
  "EQUALS",
  "COMA",
  "AND",
  "IF",
  "OR",
  "WHILE",
  "ELSE",
  "FOR",
  "DO",
  "RETURN",
  "INPUTI",
  "INPUTC",
  "INPUTD",
  "PRINT",
  "CONST",
  "ACOR",
  "CCOR",
  "MAIN",
  "ENTERO",
  "REAL",
  "CARACTER",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MODUL",
  "OP",
  "MASCARA",
  "NOT",
  "DEFAULT",
  "SWITCH",
  "CASE",
  "BREAK",
  "BOTHPOINT",
  "INCLUDE",
  "INITJAVA",
  "CALLJAVA",
  "CALLPY",
  "CALLVB"
  };
}

