/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import CodigoEjecutable.generarCodigoIntermedio;
import Errores.ErrorClass;
import Lenguajes.Compilador;
import Lenguajes.MetodosVisual;
import OptimizarCodigoIntermedio.OptimizarCodigo;
import TablaSimbolos.SymTable;

import javax.swing.JOptionPane;
import java.awt.*;
import java.io.File;

/**
 *
 * @author jhonny
 */
public class MainInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form MainInterfaz
     */
    public MainInterfaz() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        NuevoFIle = new javax.swing.JMenuItem();
        OpenFile = new javax.swing.JMenuItem();
        SaveFile = new javax.swing.JMenuItem();
        SaveAsFile = new javax.swing.JMenuItem();
        ClosePestaña = new javax.swing.JMenuItem();
        ExitProgram = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        generarCodigoIntermedio = new javax.swing.JMenuItem();
        Compilar = new javax.swing.JMenuItem();
        generarOptimizado = new javax.swing.JMenuItem();
        generarAsembler = new javax.swing.JMenuItem();
        ejecutar3dir = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        ejecutarOpti = new javax.swing.JMenuItem();
        ejecutarAsm = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTabbedPane1);

        jMenu1.setText("Archivo");

        NuevoFIle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NuevoFIle.setText("Nuevo");
        NuevoFIle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoFIleActionPerformed(evt);
            }
        });
        jMenu1.add(NuevoFIle);

        OpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        OpenFile.setText("Abrir");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(OpenFile);

        SaveFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        SaveFile.setText("Guardar");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        jMenu1.add(SaveFile);

        SaveAsFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveAsFile.setText("Guardar como");
        SaveAsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsFileActionPerformed(evt);
            }
        });
        jMenu1.add(SaveAsFile);

        ClosePestaña.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ClosePestaña.setText("Cerrar Pestaña");
        ClosePestaña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClosePestañaActionPerformed(evt);
            }
        });
        jMenu1.add(ClosePestaña);

        ExitProgram.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitProgram.setText("Salir");
        ExitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitProgramActionPerformed(evt);
            }
        });
        jMenu1.add(ExitProgram);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Generar codigo");

        generarCodigoIntermedio.setText("Generar codigo de 3 direcciones");
        generarCodigoIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarCodigoIntermedioActionPerformed(evt);
            }
        });
        jMenu2.add(generarCodigoIntermedio);

        Compilar.setText("Compilar");
        Compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompilarActionPerformed(evt);
            }
        });
        jMenu2.add(Compilar);

        generarOptimizado.setText("Codigo Optimizado");
        generarOptimizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarOptimizadoActionPerformed(evt);
            }
        });
        jMenu2.add(generarOptimizado);

        generarAsembler.setText("Codigo Assembler");
        jMenu2.add(generarAsembler);

        jMenuBar1.add(jMenu2);

        ejecutar3dir.setText("Ejecutar");

        jMenuItem9.setText("Codigo de 3 direcciones");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        ejecutar3dir.add(jMenuItem9);

        ejecutarOpti.setText("Codigo Optimiazdo");
        ejecutarOpti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarOptiActionPerformed(evt);
            }
        });
        ejecutar3dir.add(ejecutarOpti);

        ejecutarAsm.setText("Codigo Assembler");
        ejecutarAsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarAsmActionPerformed(evt);
            }
        });
        ejecutar3dir.add(ejecutarAsm);

        jMenuBar1.add(ejecutar3dir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoFIleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoFIleActionPerformed
        String name = "";
        while (name.isBlank() || name.isEmpty()) {
            name = JOptionPane.showInputDialog(this, "Ingrese el nombre de su documento");
            if (name == null) {
                return;
            }
        }
        Editor.Nuevo(jTabbedPane1, name);
    }//GEN-LAST:event_NuevoFIleActionPerformed

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        if (!Editor.Open(jTabbedPane1)) {
            //JOptionPane.showMessageDialog(this, "no se pudo abrir el archivo");
        }
    }//GEN-LAST:event_OpenFileActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        Editor.Save(jTabbedPane1);
    }//GEN-LAST:event_SaveFileActionPerformed

    private void SaveAsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsFileActionPerformed
        String name = "";
        while (name.isBlank() || name.isEmpty()) {
            name = JOptionPane.showInputDialog(this, "Ingrese el nombre de su documento");
            if (name == null) {
                return;
            }
        }
        Editor.SaveAs(name, jTabbedPane1);
    }//GEN-LAST:event_SaveAsFileActionPerformed

    private void ClosePestañaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClosePestañaActionPerformed
        try {
            ContentTab cnt = (ContentTab) this.jTabbedPane1.getSelectedComponent();
            if (!cnt.canSave()) {
                final int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar el documento?");
                if (opc == 0) {
                    if (cnt.fileName == null && cnt.fichero==null) {
                        String name = "";
                        while (name.isBlank() || name.isEmpty()) {
                            name = JOptionPane.showInputDialog(this, "Ingrese el nombre de su documento");
                            if (name == null) {
                                return;
                            }
                        }
                        cnt.fileName=name;
                    }
                    Editor.Save(jTabbedPane1);
                    this.jTabbedPane1.remove(this.jTabbedPane1.getSelectedComponent());
                }
            }
            try{
                this.jTabbedPane1.remove(this.jTabbedPane1.getSelectedComponent());
            }catch (Exception ignored){}
        } catch (Exception ex) {
            try{
                this.jTabbedPane1.remove(this.jTabbedPane1.getSelectedComponent());
            }catch (Exception ignored){}
        }
        //Editor.program_=null;
    }//GEN-LAST:event_ClosePestañaActionPerformed

    private void ExitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitProgramActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitProgramActionPerformed
Compilador compilador=null;
    private void CompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompilarActionPerformed
        compilar();

    }//GEN-LAST:event_CompilarActionPerformed

    void compilar(){
        if(Editor.program_==null){
            Editor.program_ = new ContentTab();
        }
        try{
            try{
                this.jTabbedPane1.remove(Editor.codInter);
            }catch (Exception ex){}
            ContentTab tab=(ContentTab) this.jTabbedPane1.getSelectedComponent();
            String texto=tab.getTexto();
            ErrorClass.numLine=0;
            MetodosVisual.clear();
            compilador=new Compilador(texto);
            compilador.create();
            compilador.compilar_vb();
            compilador.compilar_java();
            compilador.compilar_pyva();
            compilador.compilar_c();
            if(!compilador.errorClass.haveErrors()){
                Editor.addError(compilador.errorClass, jTabbedPane1);
                MetodosVisual.clear();
                compilador=null;
                //JOptionPane.showMessageDialog(this,"Error");
            }else{
                SymTable.fix();
                SymTable.print2();
                JOptionPane.showMessageDialog(this,"Compilacion exitosa");
            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Error "+ex.getMessage());
            if(!compilador.errorClass.haveErrors()){
                Editor.addError(compilador.errorClass, jTabbedPane1);
            }
            compilador=null;
            MetodosVisual.clear();
        }
    }
    private void generarCodigoIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarCodigoIntermedioActionPerformed
        if(compilador==null){
        return;
        }

        CodigoEjecutable.generarCodigoIntermedio codigoIntermedio = new CodigoEjecutable.generarCodigoIntermedio();
        codigoIntermedio.generar(MetodosVisual.instrucciones);
        Editor.addCodInter(jTabbedPane1);
    }//GEN-LAST:event_generarCodigoIntermedioActionPerformed



    private void generarOptimizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarOptimizadoActionPerformed
        if(compilador==null){
            return;
        }
        OptimizarCodigo op=new OptimizarCodigo();
        op.optimiar();
        op.print();
        try{
            Desktop.getDesktop().open(new File("reporte.html"));
        }catch (Exception ex){}

    }//GEN-LAST:event_generarOptimizadoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if(compilador!=null){
            //CodigoEjecutable.generarCodigoIntermedio cod=new CodigoEjecutable.generarCodigoIntermedio();
            //cod.generar(MetodosVisual.instrucciones);
            Editor.compilarCodigoC(CodigoEjecutable.generarCodigoIntermedio.codigoFinal);
        }else{
            compilar();
            if(compilador!=null){
                CodigoEjecutable.generarCodigoIntermedio cod=new CodigoEjecutable.generarCodigoIntermedio();
                cod.generar(MetodosVisual.instrucciones);
                Editor.compilarCodigoC(CodigoEjecutable.generarCodigoIntermedio.codigoFinal);
            }

        }

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void ejecutarOptiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarOptiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutarOptiActionPerformed

    private void ejecutarAsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarAsmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejecutarAsmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClosePestaña;
    private javax.swing.JMenuItem Compilar;
    private javax.swing.JMenuItem ExitProgram;
    private javax.swing.JMenuItem NuevoFIle;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JMenuItem SaveAsFile;
    private javax.swing.JMenuItem SaveFile;
    private javax.swing.JMenu ejecutar3dir;
    private javax.swing.JMenuItem ejecutarAsm;
    private javax.swing.JMenuItem ejecutarOpti;
    private javax.swing.JMenuItem generarAsembler;
    private javax.swing.JMenuItem generarCodigoIntermedio;
    private javax.swing.JMenuItem generarOptimizado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
