/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Errores.ErrorClass;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhonny
 */
public class TablaErrores extends javax.swing.JFrame {

    /**
     * Creates new form TablaErrores
     */
    public TablaErrores() {
        initComponents();
    }
    DefaultTableModel x;
    public void initDatas(ErrorClass errores){
    
        x=new DefaultTableModel();
        x.addColumn("Fila");
        x.addColumn("Columna");
        x.addColumn("Token");
        x.addColumn("Extra");
        x.addColumn("Tipo error");
        if(!errores.lexico.isEmpty()){
            errores.lexico.stream()
                    .forEach((err)->{
                    Object obj[]=new Object[5];
                    obj[0]=err.fila;
                    obj[1]=err.columna;
                    obj[2]=err.token;
                    obj[3]=err.dato;
                    obj[4]="Lexico";
                    x.addRow(obj);
                    });
        }
        if(!errores.sintactico.isEmpty()){
            errores.sintactico.stream()
                    .forEach((err)->{
                    Object obj[]=new Object[5];
                    obj[0]=err.fila;
                    obj[1]=err.columna;
                    obj[2]=err.token;
                    obj[3]=err.dato;
                    obj[4]="Sintactico";
                    x.addRow(obj);
                    });
        }
        if(!errores.semantico.isEmpty()){
            errores.semantico.stream()
                    .forEach((err)->{
                    Object obj[]=new Object[5];
                    obj[0]=err.fila;
                    obj[1]=err.columna;
                    obj[2]=err.token;
                    obj[3]=err.dato;
                    obj[4]="Semantico";
                    x.addRow(obj);
                    });
        }
        jTable1.setModel(x);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try{
            int column=this.jTable1.getSelectedColumn();
            int fila=this.jTable1.getSelectedRow();
            Object val=this.jTable1.getModel().getValueAt(fila, column);
            JOptionPane.showMessageDialog(this, String.valueOf(val));
        }catch(Exception ex){}
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaErrores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaErrores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
