#include <stdio.h>
#include <stdlib.h>

 int stack_IntHEAP[100],stack_Int[100];
 double stack_DoubleHEAP[100],stack_Double[100];
 double stack_CharHEAP[100],stack_Char[100];


 int punteroInt=0,punteroChar=0,punteroDouble=0;
 int punteroIntHEAP=0,punteroCharHEAP=0,punteroDoubleHEAP=0;
 int sizeINTHEAP=0,getch;
 int sizeCHARHEAP=0;
 int sizeDOUBLEHEAP=0;
void VB_validar_int_int(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int-1;
op_1=punteroInt-1;
stack_Int[op_1]=int_num0;
goto E1;;
E1:;
;};
void VB_factorial_int_int(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p2=punteroInt + 0;
valTmp1_Int=stack_Int[p2];
num_tmp_float=valTmp1_Int;
if ( num_tmp_float == 0 ) goto E2;
goto E3;;
E2:;
op_1=punteroInt-1;
stack_Int[op_1]=1;
goto E5;;
goto E4;;
E3:;
punteroTMPInt=1;
punteroTMPDouble=0;
punteroTMPChar=0;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_validar_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+1;
call_fun_int=stack_Int[op_1];
punteroTMPInt=1;
punteroTMPDouble=0;
punteroTMPChar=0;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=call_fun_int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_factorial_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+1;
call_fun_int=stack_Int[op_1];
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int*call_fun_int;
op_1=punteroInt-1;
stack_Int[op_1]=int_num0;
goto E5;;
E4:;
E5:;
;};
void JAVA_animal_getPromedio_float_float(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
op_1=punteroDoubleHEAP+3;
valTmp1_Double=stack_DoubleHEAP[op_1];
op_1=punteroDouble-1;
stack_Double[op_1]=valTmp1_Double;
goto E6;;
E6:;
;};
void JAVA_constru_animal_animal_float(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p1=punteroDoubleHEAP + 3;
p2=punteroDouble + 0;
valTmp2_Double=stack_Double[p2];
stack_DoubleHEAP[p1]=valTmp2_Double;
;};
void PY_mostrarSaludo_0(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf("PRESIONE 1 PARA CONTINUAR");
punteroTMPInt=0;
punteroTMPDouble=1;
punteroTMPChar=0;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_saltoLinea_0();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
;};
void PY_saltoLinea_0(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf(" \n");
;};
int main(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
punteroTMPInt=8;
punteroTMPDouble=4;
punteroTMPChar=3;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=10.5;
punteroIntHEAP=sizeINTHEAP;
punteroCharHEAP=sizeCHARHEAP;
punteroDoubleHEAP=sizeDOUBLEHEAP;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
JAVA_constru_animal_animal_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroChar+3;
stack_Int[1]=sizeINTHEAP;
sizeINTHEAP=sizeINTHEAP+4;
stack_Char[0]=sizeCHARHEAP;
sizeCHARHEAP=sizeCHARHEAP+4;
stack_Double[1]=sizeDOUBLEHEAP;
sizeDOUBLEHEAP=sizeDOUBLEHEAP+4;
punteroTMPInt=8;
punteroTMPDouble=4;
punteroTMPChar=3;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=20.5;
punteroIntHEAP=sizeINTHEAP;
punteroCharHEAP=sizeCHARHEAP;
punteroDoubleHEAP=sizeDOUBLEHEAP;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
JAVA_constru_animal_animal_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroChar+3;
stack_Int[2]=sizeINTHEAP;
sizeINTHEAP=sizeINTHEAP+4;
stack_Char[1]=sizeCHARHEAP;
sizeCHARHEAP=sizeCHARHEAP+4;
stack_Double[2]=sizeDOUBLEHEAP;
sizeDOUBLEHEAP=sizeDOUBLEHEAP+4;
punteroTMPInt=8;
punteroTMPDouble=4;
punteroTMPChar=3;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=40.5;
punteroIntHEAP=sizeINTHEAP;
punteroCharHEAP=sizeCHARHEAP;
punteroDoubleHEAP=sizeDOUBLEHEAP;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
JAVA_constru_animal_animal_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroChar+3;
stack_Int[3]=sizeINTHEAP;
sizeINTHEAP=sizeINTHEAP+4;
stack_Char[2]=sizeCHARHEAP;
sizeCHARHEAP=sizeCHARHEAP+4;
stack_Double[3]=sizeDOUBLEHEAP;
sizeDOUBLEHEAP=sizeDOUBLEHEAP+4;
punteroTMPInt=8;
punteroTMPDouble=4;
punteroTMPChar=3;
punteroIntHEAP=stack_Int[1];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[1];
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
JAVA_animal_getPromedio_float_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroDouble+4;
call_fun_float=stack_Double[op_1];
p1=punteroDouble + 0;
stack_Double[p1]=call_fun_float;
printf("VALOR ");
p1=punteroDouble + 0;
printf("%f",stack_Double[p1]);
return 0; };
