#include <stdio.h>
#include <stdlib.h>

 int stack_IntHEAP[100],stack_Int[100];
 double stack_DoubleHEAP[100],stack_Double[100];
 double stack_CharHEAP[100],stack_Char[100];


 int punteroInt=0,punteroChar=0,punteroDouble=0;
 int punteroIntHEAP=0,punteroCharHEAP=0,punteroDoubleHEAP=0;
 int sizeINTHEAP=0,getch;
 int sizeCHARHEAP=0;
 int sizeDOUBLEHEAP=0;
void VB_Incremento_int_int(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
p1=punteroInt + 0;
stack_Int[p1]=int_num0;
p1=punteroInt + 0;
stack_Int[p1]=2;
p1=punteroInt + 0;
stack_Int[p1]=3;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_1=punteroInt-1;
stack_Int[op_1]=valTmp1_Int;
goto E1;;
E1:;
;};
void PY_Mensaje_1(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p2=punteroDouble + 0;
valTmp1_Double=stack_Double[p2];
num_tmp_float=valTmp1_Double;
if ( num_tmp_float == 1 ) goto E2;
p2=punteroDouble + 0;
valTmp1_Double=stack_Double[p2];
num_tmp_float=valTmp1_Double;
if ( num_tmp_float == 2 ) goto E3;
goto E5;;
E2:;
printf("Arreglo antes de ordenarse");
goto E6;;
E3:;
printf("Arreglo depues de ordenarse");
goto E6;;
E5:;
printf("default");
goto E6;;
E6:;
;};
void PY_Mostrar_2(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf("arreglo[");
p1=punteroDouble + 0;
printf("%f",stack_Double[p1]);
printf("] = ");
p1=punteroDouble + 1;
printf("%f",stack_Double[p1]);
;};
int main(){;
   char string_asig[300];   int call_fun_int,call_fun_2_int;   char call_fun_char,call_fun_2_char;   double call_fun_float,call_fun_2_float;   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   double valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3,t_1_int;
   int t_1vector,t_2vector,t_3vector;
   double t_1Double,t_2Double,t_3Double;
   double t_1Doublevector,t_2Doublevector,t_3Doublevector,t_1_float;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2,t_1_char;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p1=punteroInt + 0;
stack_Int[p1]=10;
p1=punteroInt + 2;
stack_Int[p1]=0;
p1=punteroInt + 5;
stack_Int[p1]=0;
p1=punteroInt + 4;
p2=punteroInt + 0;
valTmp2_Int=stack_Int[p2];
stack_Int[p1]=valTmp2_Int;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_2=punteroInt+5;
valTmp2_Int=stack_Int[op_2];
op_3=punteroInt+5;
valTmp1_Int=valTmp1_Int+valTmp2_Int;
stack_Int[op_3]=valTmp1_Int;
op_3=punteroInt+6;
op_3=op_3+0;
op_3=op_3+1;
stack_Int[op_3]=7;
op_3=punteroInt+6;
op_3=op_3+1;
op_3=op_3+1;
stack_Int[op_3]=14;
op_3=punteroInt+6;
op_3=op_3+2;
op_3=op_3+1;
stack_Int[op_3]=18;
op_3=punteroInt+6;
op_3=op_3+3;
op_3=op_3+1;
stack_Int[op_3]=19;
op_3=punteroInt+6;
op_3=op_3+4;
op_3=op_3+1;
stack_Int[op_3]=21;
op_3=punteroInt+6;
op_3=op_3+5;
op_3=op_3+1;
stack_Int[op_3]=2;
op_3=punteroInt+6;
op_3=op_3+6;
op_3=op_3+1;
stack_Int[op_3]=9;
op_3=punteroInt+6;
op_3=op_3+7;
op_3=op_3+1;
stack_Int[op_3]=24;
op_3=punteroInt+6;
op_3=op_3+8;
op_3=op_3+1;
stack_Int[op_3]=29;
op_3=punteroInt+6;
op_3=op_3+9;
op_3=op_3+1;
stack_Int[op_3]=47;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=1;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_Mensaje_1();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
p1=punteroInt + 1;
stack_Int[p1]=0;
E9:;
p1=punteroInt + 1;
valTmp2_Int=stack_Int[p1];
p1=punteroInt + 0;
valTmp1_Int=stack_Int[p1];
if ( valTmp2_Int < valTmp1_Int ) goto E10;
goto E11;;
E10:;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPDouble+1;
op_1=op_1+punteroDouble;
stack_Double[op_1]=valTmp1_Int;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_3=punteroInt+6;
op_3=op_3+valTmp1_Int;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
op_3=punteroTMPDouble+2;
op_3=op_3+punteroDouble;
stack_Double[op_3]=t_1_int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_Mostrar_2();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
p1=punteroInt + 1;
stack_Int[p1]=int_num0;
goto E9;;
E11:;
p1=punteroInt + 1;
stack_Int[p1]=0;
E13:;
p2=punteroInt + 1;
valTmp1_Int=stack_Int[p2];
num_tmp_float=valTmp1_Int;
if ( num_tmp_float < 10 ) goto E14;
goto E15;;
E14:;
E16:;
p2=punteroInt + 2;
valTmp1_Int=stack_Int[p2];
num_tmp_float=valTmp1_Int;
if ( num_tmp_float < 9 ) goto E17;
goto E18;;
E17:;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_3=punteroInt+6;
op_3=op_3+valTmp1_Int;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
num_tmp_float=t_1_int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
op_3=punteroInt+6;
op_3=op_3+int_num0;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
if ( num_tmp_float < t_1_int ) goto E19;
goto E20;;
E19:;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_3=punteroInt+6;
op_3=op_3+valTmp1_Int;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
p1=punteroInt + 3;
stack_Int[p1]=t_1_int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
op_3=punteroInt+6;
op_3=op_3+int_num0;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_3=punteroInt+6;
op_3=op_3+valTmp1_Int;
op_3=op_3+1;
stack_Int[op_3]=t_1_int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
op_2=punteroInt+3;
valTmp2_Int=stack_Int[op_2];
op_3=punteroInt+6;
op_3=op_3+int_num0;
op_3=op_3+1;
stack_Int[op_3]=valTmp2_Int;
E20:;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_Incremento_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+posInt;
call_fun_int=stack_Int[op_1];
p1=punteroInt + 2;
stack_Int[p1]=call_fun_int;
goto E16;;
E18:;
p1=punteroInt + 2;
stack_Int[p1]=0;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_Incremento_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+posInt;
call_fun_int=stack_Int[op_1];
p1=punteroInt + 1;
stack_Int[p1]=call_fun_int;
goto E13;;
E15:;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_Mensaje_1();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
p1=punteroInt + 1;
stack_Int[p1]=0;
E21:;
p1=punteroInt + 1;
valTmp2_Int=stack_Int[p1];
p1=punteroInt + 0;
valTmp1_Int=stack_Int[p1];
if ( valTmp2_Int < valTmp1_Int ) goto E22;
goto E23;;
E22:;
posInt=7;
op_4=punteroInt+5;
valTmp4_Int=stack_Int[op_4];
posInt=posInt+(valTmp4_Int);
posInt=posInt+2;
punteroTMPInt=posInt;
punteroTMPDouble=5;
punteroTMPChar=0;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPDouble+1;
op_1=op_1+punteroDouble;
stack_Double[op_1]=valTmp1_Int;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_3=punteroInt+6;
op_3=op_3+valTmp1_Int;
op_3=op_3+1;
valTmp2_Int=stack_Int[op_3];
t_1_int=valTmp2_Int;
op_3=punteroTMPDouble+2;
op_3=op_3+punteroDouble;
stack_Double[op_3]=t_1_int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_Mostrar_2();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int+1;
p1=punteroInt + 1;
stack_Int[p1]=int_num0;
goto E21;;
E23:;
scanf("%d",&getch);
return 0; };
