#include <stdio.h>
#include <stdlib.h>

 int stack_IntHEAP[100],stack_Int[100];
 double stack_DoubleHEAP[100],stack_Double[100];
 double stack_CharHEAP[100],stack_Char[100];


 int punteroInt=0,punteroChar=0,punteroDouble=0;
 int punteroIntHEAP=0,punteroCharHEAP=0,punteroDoubleHEAP=0;
 int sizeINTHEAP=0,getch;
 int sizeCHARHEAP=0;
 int sizeDOUBLEHEAP=0;
void VB_Factorial_int_int(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p2=punteroInt + 0;
valTmp1_Int=stack_Int[p2];
num_tmp_float=valTmp1_Int;
if ( num_tmp_float == 0 ) goto E1;
goto E2;;
E1:;
op_1=punteroInt-1;
stack_Int[op_1]=1;
goto E4;;
goto E3;;
E2:;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int-1;
punteroTMPInt=7;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=int_num0;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_Factorial_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+7;
call_fun_2_Int=stack_Int[op_1];
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
int_num0=valTmp1_Int*call_fun_2_Int;
op_1=punteroInt-1;
stack_Int[op_1]=int_num0;
goto E4;;
E3:;
E4:;
;};
void VB_pintarNota_int(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf("\n La nota Es de ");
p1=punteroInt + 0;
printf("%d",stack_Int[p1]);
printf("\n");
;};
void JAVA_alumno_actualizarPromedio_int_int(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
E6:;
p1=punteroInt + 0;
valTmp2_Int=stack_Int[p1];
if ( valTmp2_Int == 1 ) goto E7;
p1=punteroInt + 0;
valTmp2_Int=stack_Int[p1];
if ( valTmp2_Int == 2 ) goto E8;
p1=punteroInt + 0;
valTmp2_Int=stack_Int[p1];
if ( valTmp2_Int == 3 ) goto E9;
goto E10;;
E7:;
p1=punteroIntHEAP + 0;
p2=punteroInt + 1;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
goto E10;;
E8:;
p1=punteroIntHEAP + 1;
p2=punteroInt + 1;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
goto E10;;
E9:;
p1=punteroIntHEAP + 2;
p2=punteroInt + 1;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
goto E10;;
E10:;
;};
void JAVA_alumno_pintarPromedio(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf("EL PROMEDIO ES DE ");
p1=punteroDoubleHEAP + 0;
printf("%f",stack_DoubleHEAP[p1]);
printf("\n");
;};
void JAVA_alumno_calcularPromedio_int(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
op_1=punteroIntHEAP+0;
valTmp1_Int=stack_IntHEAP[op_1];
op_2=punteroIntHEAP+1;
valTmp2_Int=stack_IntHEAP[op_2];
int_num0=valTmp1_Int+valTmp2_Int;
op_2=punteroIntHEAP+2;
valTmp2_Int=stack_IntHEAP[op_2];
int_num1=int_num0+valTmp2_Int;
int_num0=int_num1/3;
p1=punteroDoubleHEAP + 0;
stack_DoubleHEAP[p1]=int_num0;
;};
void JAVA_alumno_getPromedio_float_float(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
op_1=punteroDoubleHEAP+0;
valTmp1_Double=stack_DoubleHEAP[op_1];
op_1=punteroDouble-1;
stack_Double[op_1]=valTmp1_Double;
goto E15;;
E15:;
;};
void JAVA_constru_alumno_alumno_int_int_int(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p1=punteroIntHEAP + 0;
p2=punteroInt + 0;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
p1=punteroIntHEAP + 1;
p2=punteroInt + 1;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
p1=punteroIntHEAP + 2;
p2=punteroInt + 2;
valTmp2_Int=stack_Int[p2];
stack_IntHEAP[p1]=valTmp2_Int;
;};
void PY_validarCurso_1(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
printf("EVALUANDO NOTA: ");
p1=punteroDouble + 0;
printf("%f",stack_Double[p1]);
p2=punteroDouble + 0;
valTmp1_Double=stack_Double[p2];
num_tmp_float=valTmp1_Double;
if ( num_tmp_float < 50 ) goto E17;
goto E18;;
E17:;
printf(" REPROBADO \n");
goto E19;;
E18:;
printf(" APROBADO NOTA \n");
goto E19;;
E19:;
;};
int main(){;
   int call_fun_Int_2_Int, call_fun_Int,call_fun_2_Int,call_fun_Int_Int,call_fun_2_Int_2_Int;
   double call_fun_Double_2_Double, call_fun_Double,call_fun_2_Double,call_fun_Double_Double,call_fun_2_Double_2_Double;

   char call_fun_Char_2_Char,call_fun_Char,call_fun_2_Char,call_fun_Char_Char,call_fun_2_Char_2_Char;
   int p1,op_1,op_2,op_3,op_4,p2;
   int valTmp1_Int,valTmp2_Int,valTmp4_Int;
   int valTmp1_Double,valTmp2_Double,valTmp4_Double;
   char valTmp1_Char,valTmp2_Char,valTmp4_Char;
   int int_num0vector,int_num1vector;
   double double_num0vector,double_num1vector;
   char char_num0vector,char_num1vector;
   int t_1,t_2,t_3;
   int t_1vector,t_2vector,t_3vector;
   int int_num0,int_num1,int_num2,int_num3;
   int int_ex_num0,int_ex_num1,int_ex_num2;
   double double_ex_num0,double_ex_num1,double_ex_num2;
   char char_ex_num0,char_ex_num1,char_ex_num2;
   int punteroTMPInt;
   int punteroTMPChar;
   int punteroTMPDouble;
   int num_tmp_int;
   int posDouble,posInt,posChar;
   double float_num0,float_num1,float_num3,float_num2;
   double num_tmp_float,num_tmp_double;
   char num_tmp_char;
   char char_num0,char_num1,char_num3,char_num2;
p1=punteroInt + 4;
stack_Int[p1]=0;
printf("Ingrese la nota del curso1 \n ");
p1=punteroInt + 0;
scanf("%d",&stack_Int[p1]);
printf("Ingrese la nota del curso2 \n ");
p1=punteroInt + 1;
scanf("%d",&stack_Int[p1]);
printf("Ingrese la nota del curso3 \n ");
p1=punteroInt + 2;
scanf("%d",&stack_Int[p1]);
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+2;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+3;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=sizeINTHEAP;
punteroCharHEAP=sizeCHARHEAP;
punteroDoubleHEAP=sizeDOUBLEHEAP;
JAVA_constru_alumno_alumno_int_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroChar+2;
stack_Int[5]=sizeINTHEAP;
sizeINTHEAP=sizeINTHEAP+6;
stack_Char[0]=sizeCHARHEAP;
sizeCHARHEAP=sizeCHARHEAP+6;
stack_Double[0]=sizeDOUBLEHEAP;
sizeDOUBLEHEAP=sizeDOUBLEHEAP+6;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=3;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_calcularPromedio_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_pintarPromedio();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_pintarNota_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_pintarNota_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_pintarNota_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_getPromedio_float_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroDouble+2;
call_fun_Double=stack_Double[op_1];
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=call_fun_Double;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_validarCurso_1();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=7;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=5;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
VB_Factorial_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroInt+7;
call_fun_Int=stack_Int[op_1];
p1=punteroInt + 3;
stack_Int[p1]=call_fun_Int;
printf("\n VALOR: ");
p1=punteroInt + 3;
printf("%d",stack_Int[p1]);
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=1;
op_3=punteroTMPInt+2;
op_3=op_3+punteroInt;
stack_Int[op_3]=60;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_actualizarPromedio_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=2;
op_3=punteroTMPInt+2;
op_3=op_3+punteroInt;
stack_Int[op_3]=60;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_actualizarPromedio_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=3;
op_3=punteroTMPInt+2;
op_3=op_3+punteroInt;
stack_Int[op_3]=60;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_actualizarPromedio_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
scanf("%d",&getch);
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=3;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_calcularPromedio_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_pintarPromedio();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[5];
punteroCharHEAP=stack_Char[0];
punteroDoubleHEAP=stack_Double[0];
JAVA_alumno_getPromedio_float_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroDouble+2;
call_fun_Double=stack_Double[op_1];
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=call_fun_Double;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_validarCurso_1();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
printf("Desea limpiar la pantalla? Presione 1");
p1=punteroInt + 4;
scanf("%d",&stack_Int[p1]);
p2=punteroInt + 4;
valTmp1_Int=stack_Int[p2];
num_tmp_float=valTmp1_Int;
if ( num_tmp_float == 1 ) goto E21;
goto E22;;
E21:;
system("clear");;
E22:;
printf("\n DATOS ESTUDIANTE 2 \n");
printf("Ingrese la nota del curso1 \n ");
p1=punteroInt + 0;
scanf("%d",&stack_Int[p1]);
printf("Ingrese la nota del curso2 \n ");
p1=punteroInt + 1;
scanf("%d",&stack_Int[p1]);
printf("Ingrese la nota del curso3 \n ");
p1=punteroInt + 2;
scanf("%d",&stack_Int[p1]);
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_1=punteroInt+0;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+1;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
op_1=punteroInt+1;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+2;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
op_1=punteroInt+2;
valTmp1_Int=stack_Int[op_1];
op_1=punteroTMPInt+3;
op_1=op_1+punteroInt;
stack_Int[op_1]=valTmp1_Int;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=sizeINTHEAP;
punteroCharHEAP=sizeCHARHEAP;
punteroDoubleHEAP=sizeDOUBLEHEAP;
JAVA_constru_alumno_alumno_int_int_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroChar+2;
stack_Int[6]=sizeINTHEAP;
sizeINTHEAP=sizeINTHEAP+6;
stack_Char[1]=sizeCHARHEAP;
sizeCHARHEAP=sizeCHARHEAP+6;
stack_Double[1]=sizeDOUBLEHEAP;
sizeDOUBLEHEAP=sizeDOUBLEHEAP+6;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPInt+1;
op_3=op_3+punteroInt;
stack_Int[op_3]=3;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[6];
punteroCharHEAP=stack_Char[1];
punteroDoubleHEAP=stack_Double[1];
JAVA_alumno_calcularPromedio_int();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
punteroIntHEAP=stack_Int[6];
punteroCharHEAP=stack_Char[1];
punteroDoubleHEAP=stack_Double[1];
JAVA_alumno_getPromedio_float_float();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
op_1=punteroDouble+2;
call_fun_Double=stack_Double[op_1];
punteroTMPInt=9;
punteroTMPDouble=2;
punteroTMPChar=2;
op_3=punteroTMPDouble+1;
op_3=op_3+punteroDouble;
stack_Double[op_3]=call_fun_Double;
punteroInt=punteroTMPInt+punteroInt;
punteroDouble=punteroTMPDouble+punteroDouble;
punteroChar=punteroTMPChar+punteroChar;
punteroInt=1+punteroInt;
punteroDouble=1+punteroDouble;
punteroChar=1+punteroChar;
PY_validarCurso_1();
punteroInt=punteroInt-punteroTMPInt;
punteroDouble=punteroDouble-punteroTMPDouble;
punteroChar=punteroChar-punteroTMPChar;
punteroInt=punteroInt-1;
punteroDouble=punteroDouble-1;
punteroChar=punteroChar-1;
return 0; };
