// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/GramaticaPython/pylex.jflex

package GramaticaPython;
import java_cup.runtime.Symbol;
import Errores.ErrorClass;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class pylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int VERIFY = 2;
  public static final int STRING = 4;
  public static final int CHAR = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  3,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  4,  4, 
     5,  6,  7,  4,  8,  9,  4,  4, 10, 11, 12, 13, 14, 15, 16, 17, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19,  4, 20, 21, 20,  4, 
     4, 22,  8,  8,  8,  8,  8, 23,  8,  8,  8,  8,  8, 24,  8, 25, 
    26,  8, 27,  8,  8,  8,  8,  8,  8,  8,  8,  4, 28,  4,  4,  8, 
     4, 29,  8, 30, 31, 32, 33, 34, 35, 36,  8,  8, 37,  8, 38, 39, 
    40,  8, 41, 42, 43, 44,  8, 45,  8,  8,  8,  4,  4,  4,  4,  0, 
     0,  0,  0,  0,  0, 46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     4,  4,  8,  8,  8,  8,  4,  4,  4,  4,  8,  4,  4,  0,  4,  4, 
     4,  4,  4,  4,  4,  8,  4,  4,  4,  4,  8,  4,  4,  4,  4,  4, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  4,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  4,  8,  8,  8,  8,  8,  8,  8,  8
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\2\1\1\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\13\5\1\22\1\23\1\22"+
    "\1\24\1\25\2\24\1\26\1\24\1\20\2\0\6\5"+
    "\1\27\1\30\1\5\1\31\4\5\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\0\1\42\1\43"+
    "\1\5\1\44\3\5\1\45\1\5\1\46\4\5\1\0"+
    "\1\5\1\47\1\50\6\5\1\0\3\5\1\51\1\52"+
    "\1\5\1\53\1\0\3\5\1\54\1\0\3\5\1\0"+
    "\2\5\1\55\1\0\1\56\1\5\1\57\1\60";

  private static int [] zzUnpackAction() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\274\0\u01a7\0\u01d6\0\274\0\274\0\274\0\274"+
    "\0\274\0\u0205\0\274\0\u0234\0\274\0\u0178\0\274\0\u0263"+
    "\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\u03db"+
    "\0\u040a\0\u0439\0\274\0\274\0\u0468\0\u0497\0\274\0\u04c6"+
    "\0\274\0\274\0\u04f5\0\274\0\u0524\0\u0553\0\u0582\0\u05b1"+
    "\0\u05e0\0\u060f\0\u063e\0\u066d\0\u01a7\0\u069c\0\u06cb\0\u01a7"+
    "\0\u06fa\0\u0729\0\u0758\0\u0787\0\274\0\274\0\274\0\274"+
    "\0\274\0\274\0\274\0\274\0\u07b6\0\274\0\u01a7\0\u07e5"+
    "\0\u01a7\0\u0814\0\u0843\0\u0872\0\u01a7\0\u08a1\0\u01a7\0\u08d0"+
    "\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u01a7\0\u01a7\0\u09ea"+
    "\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62"+
    "\0\u0b91\0\u01a7\0\u01a7\0\u0bc0\0\u01a7\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\u0c7c\0\u01a7\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0d67\0\u0d96"+
    "\0\u0dc5\0\u01a7\0\u0df4\0\u01a7\0\u0e23\0\274\0\u01a7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\0\1\5\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\5\1\23\1\24\1\25\1\26\1\27\6\13\1\5"+
    "\1\30\1\31\1\32\1\33\1\34\2\13\1\35\1\13"+
    "\1\36\1\37\1\40\1\41\3\13\1\42\1\0\7\43"+
    "\1\44\24\43\1\45\22\43\7\46\1\47\24\46\1\50"+
    "\22\46\7\51\1\52\24\51\1\53\22\51\60\0\1\6"+
    "\56\0\2\7\2\0\1\7\56\0\1\10\76\0\1\54"+
    "\31\0\1\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\22\13\11\0\1\55\67\0\1\24\54\0\1\56"+
    "\1\0\1\24\34\0\1\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\11\13\1\57\11\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\6\13\1\60\14\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\3\13"+
    "\1\61\17\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\10\13\1\62\12\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\10\13\1\63\1\13\1\64\10\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\4\13"+
    "\1\65\4\13\1\66\11\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\12\13\1\67\10\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\14\13\1\70\6\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\14\13"+
    "\1\71\6\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\1\72\2\13\1\73\17\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\6\13\1\74\13\13\7\0"+
    "\1\75\36\0\1\76\2\0\1\77\1\0\1\100\3\0"+
    "\7\46\1\0\56\46\1\101\47\46\7\0\1\101\36\0"+
    "\1\102\2\0\1\103\1\0\1\104\35\0\1\105\46\0"+
    "\1\106\34\0\1\13\7\0\1\13\11\0\1\13\3\0"+
    "\6\13\1\0\2\13\1\107\20\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\1\110\22\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\4\13\1\111\16\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\7\13"+
    "\1\112\5\13\1\113\5\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\12\13\1\114\10\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\14\13\1\115\6\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\16\13"+
    "\1\116\4\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\16\13\1\117\4\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\7\13\1\120\13\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\11\13\1\121\11\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\16\13"+
    "\1\122\4\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\7\13\1\123\12\13\33\0\1\124\23\0\1\13"+
    "\7\0\1\13\11\0\1\13\3\0\6\13\1\0\14\13"+
    "\1\125\6\13\7\0\1\13\11\0\1\13\3\0\6\13"+
    "\1\0\4\13\1\126\16\13\7\0\1\13\11\0\1\13"+
    "\3\0\6\13\1\0\3\13\1\127\17\13\7\0\1\13"+
    "\11\0\1\13\3\0\6\13\1\0\1\130\22\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\7\13\1\131"+
    "\13\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\11\13\1\132\11\13\7\0\1\13\11\0\1\13\3\0"+
    "\6\13\1\0\5\13\1\133\15\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\17\13\1\134\3\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\10\13\1\135"+
    "\11\13\31\0\1\136\25\0\1\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\7\13\1\137\13\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\16\13\1\140"+
    "\4\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\11\13\1\141\11\13\7\0\1\13\11\0\1\13\3\0"+
    "\6\13\1\0\16\13\1\142\4\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\3\13\1\143\17\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\14\13\1\144"+
    "\6\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\3\13\1\145\16\13\27\0\1\146\27\0\1\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\11\13\1\147"+
    "\11\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\7\13\1\150\13\13\7\0\1\13\11\0\1\13\3\0"+
    "\6\13\1\0\13\13\1\151\7\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\11\13\1\152\10\13\33\0"+
    "\1\153\23\0\1\13\7\0\1\13\11\0\1\13\3\0"+
    "\6\13\1\0\13\13\1\154\7\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\11\13\1\155\11\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\17\13\1\156"+
    "\2\13\26\0\1\157\30\0\1\13\7\0\1\13\11\0"+
    "\1\13\3\0\6\13\1\0\17\13\1\160\3\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\13\13\1\161"+
    "\7\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\16\13\1\162\3\13\30\0\1\163\26\0\1\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\16\13\1\164"+
    "\4\13\7\0\1\13\11\0\1\13\3\0\6\13\1\0"+
    "\17\13\1\165\2\13\26\0\1\166\30\0\1\13\7\0"+
    "\1\13\11\0\1\13\3\0\6\13\1\0\16\13\1\167"+
    "\3\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3666];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\4\1\1\11\2\1\5\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\13\1\2\11\2\1\1\11"+
    "\1\1\2\11\1\1\1\11\2\0\16\1\10\11\1\0"+
    "\1\11\15\1\1\0\11\1\1\0\7\1\1\0\4\1"+
    "\1\0\3\1\1\0\3\1\1\0\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[119];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();
 public int fila,columna=0;
    public ErrorClass errores=new ErrorClass();
    public boolean add=true;
    private Symbol symbol(int type, Object value) {
    fila=yyline+1;
           columna+=yycolumn+1;
        return new Symbol(type, yyline+1, yycolumn+1, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public pylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { if(add){
    fila=yyline+1;
      columna+=yycolumn+1;
    errores.AddError(0,yyline+1,yycolumn+1,yytext());}
            }
            // fall through
          case 49: break;
          case 2:
            { 
            }
            // fall through
          case 50: break;
          case 3:
            { if(add){return symbol(sym.SALTO_LINEA,new String(yytext()));}
            }
            // fall through
          case 51: break;
          case 4:
            { yybegin(VERIFY);
            }
            // fall through
          case 52: break;
          case 5:
            { if(add){return symbol(sym.ID,new String(yytext()));}
            }
            // fall through
          case 53: break;
          case 6:
            { if(add){return symbol(sym.MODUL,new String(yytext()));}
            }
            // fall through
          case 54: break;
          case 7:
            { if(add){return symbol(sym.AP,new String(yytext()));}
            }
            // fall through
          case 55: break;
          case 8:
            { if(add){return symbol(sym.CP,new String(yytext()));}
            }
            // fall through
          case 56: break;
          case 9:
            { if(add){return symbol(sym.MUL,new String(yytext()));}
            }
            // fall through
          case 57: break;
          case 10:
            { if(add){return symbol(sym.SUM,new String(yytext()));}
            }
            // fall through
          case 58: break;
          case 11:
            { if(add){return symbol(sym.COMA,new String(yytext()));}
            }
            // fall through
          case 59: break;
          case 12:
            { if(add){return symbol(sym.RES,new String(yytext()));}
            }
            // fall through
          case 60: break;
          case 13:
            { if(add){return symbol(sym.DIV,new String(yytext()));}
            }
            // fall through
          case 61: break;
          case 14:
            { if(add){return symbol(sym.ENTERO,new Integer(yytext()));}
            }
            // fall through
          case 62: break;
          case 15:
            { if(add){return symbol(sym.TWOPOINT,new String(yytext()));}
            }
            // fall through
          case 63: break;
          case 16:
            { if(add){return symbol(sym.OP,new String(yytext()));}
            }
            // fall through
          case 64: break;
          case 17:
            { if(add){return symbol(sym.EQUALS,new String(yytext()));}
            }
            // fall through
          case 65: break;
          case 18:
            { string.append(yytext());yybegin(CHAR);
            }
            // fall through
          case 66: break;
          case 19:
            { yybegin(YYINITIAL);
                                        String val=string.toString();
                                        string=new StringBuffer();
                                       if(add){ return symbol(sym.CADENA,val);}
            }
            // fall through
          case 67: break;
          case 20:
            { string.append(yytext());yybegin(STRING);
            }
            // fall through
          case 68: break;
          case 21:
            { yybegin(YYINITIAL);
                                        String val=string.toString();
                                        string=new StringBuffer();
                                     if(add){   return symbol(sym.CADENA,val);}
            }
            // fall through
          case 69: break;
          case 22:
            { yybegin(YYINITIAL);
                                        String val=string.toString();
                                        string=new StringBuffer();
                                        char y=val.charAt(0);
                                     if(add){   return symbol(sym.CARACTER,y);}
            }
            // fall through
          case 70: break;
          case 23:
            { if(add){return symbol(sym.IF,new String(yytext()));}
            }
            // fall through
          case 71: break;
          case 24:
            { if(add){return symbol(sym.IN,new String(yytext()));}
            }
            // fall through
          case 72: break;
          case 25:
            { if(add){return symbol(sym.OR,new String(yytext()));}
            }
            // fall through
          case 73: break;
          case 26:
            { string.append('\"'); yybegin(CHAR);
            }
            // fall through
          case 74: break;
          case 27:
            { string.append('\n'); yybegin(CHAR);
            }
            // fall through
          case 75: break;
          case 28:
            { string.append('\r'); yybegin(CHAR);
            }
            // fall through
          case 76: break;
          case 29:
            { string.append('\t'); yybegin(CHAR);
            }
            // fall through
          case 77: break;
          case 30:
            { string.append('\"'); yybegin(STRING);
            }
            // fall through
          case 78: break;
          case 31:
            { string.append('\n'); yybegin(STRING);
            }
            // fall through
          case 79: break;
          case 32:
            { string.append('\r'); yybegin(STRING);
            }
            // fall through
          case 80: break;
          case 33:
            { string.append('\t'); yybegin(STRING);
            }
            // fall through
          case 81: break;
          case 34:
            { if(add){return symbol(sym.REAL,new Double(yytext()));}
            }
            // fall through
          case 82: break;
          case 35:
            { if(add){return symbol(sym.AND,new String(yytext()));}
            }
            // fall through
          case 83: break;
          case 36:
            { if(add){return symbol(sym.DEF,new String(yytext()));}
            }
            // fall through
          case 84: break;
          case 37:
            { if(add){return symbol(sym.FOR,new String(yytext()));}
            }
            // fall through
          case 85: break;
          case 38:
            { if(add){return symbol(sym.NOT,new String(yytext()));}
            }
            // fall through
          case 86: break;
          case 39:
            { if(add){return symbol(sym.ELSEIF,new String(yytext()));}
            }
            // fall through
          case 87: break;
          case 40:
            { if(add){return symbol(sym.ELSE,new String(yytext()));}
            }
            // fall through
          case 88: break;
          case 41:
            { if(add){return symbol(sym.PRINT,new String(yytext()));}
            }
            // fall through
          case 89: break;
          case 42:
            { if(add){return symbol(sym.RANGE,new String(yytext()));}
            }
            // fall through
          case 90: break;
          case 43:
            { if(add){return symbol(sym.WHILE,new String(yytext()));}
            }
            // fall through
          case 91: break;
          case 44:
            { if(add){return symbol(sym.RETURN,new String(yytext()));}
            }
            // fall through
          case 92: break;
          case 45:
            { if(add){return symbol(sym.INPUTI,new String(yytext()));}
            }
            // fall through
          case 93: break;
          case 46:
            { if(add){return symbol(sym.INPUTC,new String(yytext()));}
            }
            // fall through
          case 94: break;
          case 47:
            { if(add){add=false;
     yyclose();
    return symbol(sym.CODC,new String(yytext()));}
            }
            // fall through
          case 95: break;
          case 48:
            { if(add){return symbol(sym.INPUTD,new String(yytext()));}
            }
            // fall through
          case 96: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " char:" + yychar + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java pylex [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        pylex scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new pylex(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
