
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package GramaticaPython;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQUALS = 22;
  public static final int RES = 17;
  public static final int ENTERO = 31;
  public static final int INPUTI = 34;
  public static final int INPUTD = 36;
  public static final int INPUTC = 35;
  public static final int FOR = 5;
  public static final int CP = 13;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int ELSEIF = 21;
  public static final int TWOPOINT = 9;
  public static final int RANGE = 14;
  public static final int CARACTER = 33;
  public static final int IN = 11;
  public static final int OR = 25;
  public static final int OP = 15;
  public static final int DIV = 19;
  public static final int IF = 4;
  public static final int CODC = 7;
  public static final int ID = 29;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int COMA = 10;
  public static final int CADENA = 27;
  public static final int REAL = 32;
  public static final int ELSE = 3;
  public static final int WHILE = 2;
  public static final int SUM = 16;
  public static final int SALTO_LINEA = 28;
  public static final int DEF = 23;
  public static final int AP = 12;
  public static final int MODUL = 20;
  public static final int PY = 8;
  public static final int PRINT = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WHILE",
  "ELSE",
  "IF",
  "FOR",
  "RETURN",
  "CODC",
  "PY",
  "TWOPOINT",
  "COMA",
  "IN",
  "AP",
  "CP",
  "RANGE",
  "OP",
  "SUM",
  "RES",
  "MUL",
  "DIV",
  "MODUL",
  "ELSEIF",
  "EQUALS",
  "DEF",
  "AND",
  "OR",
  "NOT",
  "CADENA",
  "SALTO_LINEA",
  "ID",
  "PRINT",
  "ENTERO",
  "REAL",
  "CARACTER",
  "INPUTI",
  "INPUTC",
  "INPUTD"
  };
}

